### ISSUE TITLE
packages get stuck in downloading or finding state on Windows

### ISSUE THREAD

**Issue by BryanCrotaz** [rstacruz/pnpm#292] opened 2016-08-13 12:04 UTC
Using 
```
npm i -g rstacruz/pnpm
pnpm install
```
in an ember-cli project

tens of packages get stuck in `finding` or `downloading` state
```
  strip-bom ^2.0.0                                                finding ·
  has-ansi ^0.1.0                                                 finding ·
  depd ~1.1.0                                                     finding ·
  http-errors ~1.5.0                                              finding ·
  ember-cli-app-version ^1.0.0                                    finding ·
  broccoli-merge-trees ^1.1.1                                     finding ·
  extend ^3.0.0                                                     3.6.1 ·
  on-finished ~2.3.0                                              finding ·
  quick-temp ^0.1.5                                                 0.1.5 ✓
  mute-stream 0.0.4                                                 0.0.4 ✓
  once ^1.3.0                                                       1.3.3 ✓
  semver ^4.3.1                                                   finding ·
  graceful-fs ^4.1.2                                              finding ·
  resolve ^1.1.2                                                  finding ·
  ember-cli-app-version ^1.0.0                                      1.1.1 ·
  prelude-ls ~1.1.2                                               finding ·
  walker ~1.0.5                                                   finding ·
  lodash ~2.4.1                                                     2.4.2 ✓
  graceful-fs ~4.1.2                                                4.1.5 ✓
  mkdirp ~0.5.0                                                     0.5.0 ✓
  rimraf ~2.4.3                                                     2.4.5 ✓
  ansi-styles ~1.0.0                                              finding ·
  recast ^0.10.10                                     downloading 0.10.43 ↓
  raw-body ~2.1.7                                                 finding ·
  commander ~2.1.0                                                  2.1.0 ✓
  eventemitter3 1.x.x                                               1.0.0 ✓
  lodash.merge ^3.3.2                                               3.3.2 ·
  on-finished ~2.3.0                                              finding ·
  mkdirp ~0.5.0                                                   finding ·
  mkdirp ~0.5.0                                                   finding ·
  mkdirp ~0.5.0                                                     0.5.6 ✓
  rsvp ^3.0.21                                                      3.2.1 ✓
  broccoli-plugin ^1.2.1                                            1.4.1 ·
  ember-export-application-global ^1.0.5                          finding ·
  mkdirp ~0.5.0                                                   finding ·
  broccoli-filter ^1.2.2                                            1.3.0 ·
  bower-endpoint-parser 0.2.2                                     finding ·
  broccoli-merge-trees ^1.1.1                                     finding ·
  path-to-regexp 0.1.7                                              0.1.7 ✓
  range-parser ~1.2.0                                        queued 1.2.4 ↓
  send 0.14.1                                                      0.14.1 ✓
  resolve ^1.1.2                                                  finding ·
  uglify-js ^2.6.0                                                finding ·
  esprima-fb ~15001.1001.0-dev-harmony-fb     15001.1001.0-dev-harmony-fb ✓
  private ~0.1.5                                                    0.1.6 ✓
  recast 0.10.33                                                  0.10.33 ·
  through ~2.3.8                                                    2.3.8 ✓
  negotiator 0.6.1                                                  0.6.1 ✓
  colors 1.0.3                                                      1.0.3 ✓
  rimraf ^2.4.4                                                   finding ·
  merge ^1.1.3                                                    finding ·
  uglify-js ^2.6.0                                                  2.9.0 ✓
  ansi-styles ~1.0.0                                    downloading 1.0.1 ↓
  os-tmpdir ~1.0.1                                                finding ·
  depd ~1.1.0                                                     finding ·
  rx-lite ^3.1.2                                                    3.1.2 ✓
  os-tmpdir ~1.0.1                                                  1.0.2 ·
  concat-map 0.0.1                                                finding ·
  loader.js ^4.0.1                                                finding ·
  merge ^1.1.3                                                      1.3.2 ·
  inherits ~2.0.1                                                 finding ·
  depd ~1.1.0                                                       1.1.0 ✓
  has-color ~0.1.0                                                finding ·
  broccoli-writer ~0.1.1                                          finding ·
  npm 2.14.21                                                     2.14.21 ·
  ember-cli-app-version ^1.0.0                               queued 1.0.0 ↓
  os-tmpdir ~1.0.1                                                     OK
```
At the end, an error:
` ! Invalid Version: undefined`

**Comment by BryanCrotaz** [comment] 2016-08-13 12:05
package.json
```
{
  "name": "ember-dds",
  "version": "0.0.0",
  "description": "The default blueprint for ember-cli addons.",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember try:testall"
  },
  "repository": {
    "type": "git",
    "url": "git+ssh://git@bitbucket.org/silvercurve/ember-dds.git"
  },
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "broccoli-clext": "^0.5.2",
    "ember-ajax": "0.7.1",
    "ember-cli": "2.5.0",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-code-coverage": "^0.2.2",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-jshint": "^1.0.0",
    "ember-cli-qunit": "^1.4.0",
    "ember-cli-release": "0.2.8",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.5.0",
    "ember-disable-prototype-extensions": "^1.1.0",
    "ember-export-application-global": "^1.0.5",
    "ember-load-initializers": "^0.5.1",
    "ember-resolver": "^2.0.3",
    "ember-try": "^0.2.2",
    "ember-websockets": "3.0.0",
    "loader.js": "^4.0.1"
  },
  "keywords": [
    "ember-addon"
  ],
  "dependencies": {
    "ember-cli-babel": "^5.1.6",
    "ember-cli-htmlbars": "^1.0.3"
  },
  "ember-addon": {
    "configPath": "tests/dummy/config"
  }
}
```

**Comment by zkochan** [comment] 2016-08-13 12:08
In my case nothing gets stuck but I do get an `! Invalid Version: undefined` at the end.
I'll try to figure this out

**Comment by BryanCrotaz** [comment] 2016-08-13 12:10
It may just be a console issue - if I run `pnpm install` again it completes in about a second with
```
C:\projects\ember-dds>pnpm install
  broccoli-asset-rev ^2.4.2                                            OK ✓
  ember-cli-babel ^5.1.6                                               OK ✓
  ember-cli-htmlbars ^1.0.3                                            OK ✓
  ember-cli-code-coverage ^0.2.2                                       OK ✓
  ember-cli-app-version ^1.0.0                                         OK ✓
  ember-cli 2.5.0                                                      OK ✓
  ember-ajax 0.7.1                                                     OK ✓
  broccoli-clext ^0.5.2                                                OK ✓
  ember-cli-dependency-checker ^1.2.0                                  OK ✓
  ember-cli-htmlbars-inline-precompile ^0.3.1                          OK ✓
  ember-cli-inject-live-reload ^1.4.0                                  OK ✓
  ember-cli-sri ^2.1.0                                                 OK ✓
  ember-cli-release 0.2.8                                              OK ✓
  ember-disable-prototype-extensions ^1.1.0                            OK ✓
  ember-data ^2.5.0                                                    OK ✓
  ember-export-application-global ^1.0.5                               OK ✓
  ember-resolver ^2.0.3                                                OK ✓
  ember-load-initializers ^0.5.1                                       OK ✓
  ember-websockets 3.0.0                                               OK ✓
  loader.js ^4.0.1                                                     OK ✓
```

**Comment by BryanCrotaz** [comment] 2016-08-13 12:11
However the install didn't work correctly:

```
C:\projects\ember-dds>ember serve
DEPRECATION: ember-try is now included with ember-cli. Including it in your package.json is unnecessary.
Cannot find module 'glob'
Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (C:\projects\ember-dds\server\index.js:13:20)
    at Class.module.exports.Task.extend.processAppMiddlewares (C:\projects\ember-dds\node_modules\.store\ember-cli@2.5.0\_\lib\tasks\server\express-server.js:126:14)
    at Class.<anonymous> (C:\projects\ember-dds\node_modules\.store\ember-cli@2.5.0\_\lib\tasks\server\express-server.js:220:21)
    at lib$rsvp$$internal$$tryCatch (C:\projects\ember-dds\node_modules\.store\rsvp@3.2.1\_\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\projects\ember-dds\node_modules\.store\rsvp@3.2.1\_\dist\rsvp.js:1048:17)
    at C:\projects\ember-dds\node_modules\.store\rsvp@3.2.1\_\dist\rsvp.js:331:11
```

**Comment by zkochan** [comment] 2016-08-13 12:14
Seems like the error is happening when checking the peer dependencies

**Comment by BryanCrotaz** [comment] 2016-08-13 12:16
To run the full process yourself:
```
npm install -g ember-cli
npm install -g bower
ember new myapp
cd myapp
pnpm install
bower install
ember serve
```
Then browse to `//localhost:4200` and you should see an hello world web page

**Comment by zkochan** [comment] 2016-08-13 12:50
You can install pnpm from the git-fix branch. It should solve your issue.

But that's not the final fix because the issue is deeper and affects several features of pnpm.

Thanks for reporting this.

**Comment by BryanCrotaz** [comment] 2016-08-13 16:06
results from git-fix branch
```
  debug ^2.1.3                                                    finding ·
  make-array ^0.1.2                                               finding ·
  deep-is ~0.1.3                                                    0.1.3 ✓
  type-check ~0.3.2                                                 0.3.2 ✓
  heimdalljs ^0.2.1                                               finding ·
  git-repo-info ^1.0.4                                            finding ·
  inherits 2.0.1                                                    2.0.1 ✓
  setprototypeof 1.0.1                                              1.0.1 ✓
  statuses >= 1.3.0 < 2                                             1.3.0 ✓
  ember-resolver ^2.0.3                                           finding ·
  source-map ~0.5.1                                                 0.5.6 ✓
  ember-cli-app-version ^1.0.0                                    finding ·
  mime-types ~2.1.11                                               2.1.11 ✓
  escape-html ~1.0.3                                                1.0.3 ✓
  heimdalljs ^0.2.1                                               finding ·
  debug ^2.1.1                                                      2.2.0 ✓
  matcher-collection ^1.0.1                                       finding ·
  fs-extra ^0.26.0                                                 0.26.7 ✓
  rimraf ^2.3.2                                                     2.5.4 ✓
  semver ^5.1.0                                                   finding ·
  walk-sync ^0.2.6                                                finding ·
  babel-core ^5.8.38                                              finding ·
  babel-plugin-htmlbars-inline-precompile ^0.1.0                  finding ·
  setprototypeof 1.0.1                                            finding ·
  ember-cli-app-version ^1.0.0                                    finding ·
  mime-db ~1.23.0                                                  1.23.0 ✓
  mkdirp ^0.5.0                                                   finding ·
  sane ^1.1.1                                                       1.1.5 ·
  is-utf8 ^0.2.0                                                    0.2.3 ✓
  ember-load-initializers ^0.5.1                                  finding ·
  ember-cli-app-version ^1.0.0                                    finding ·
  minimatch 2 || 3                                                  3.0.3 ✓
  ember-cli-app-version ^1.0.0                                      1.0.0 ✓
  ember-cli-app-version ^1.0.0                                      1.0.0 ·
  matcher-collection ^1.0.1                                         1.0.1 ✓
  cli 0.6.x                                                         0.6.6 ✓
  console-browserify 1.1.x                                          1.1.0 ✓
  broccoli-concat ^2.2.0                                          finding ·
  ember-cli-app-version ^1.0.0                                      1.0.0 ✓
  minimatch 2.0.x                                                  2.0.10 ✓
  shelljs 0.3.x                                                     0.3.0 ✓
  ember-cli-htmlbars-inline-precompile ^0.3.1                     finding ·
  async 1.x                                                         1.5.2 ✓
  loader.js ^4.0.1                                      downloading 4.0.1 ↓
  ember-cli-app-version ^1.0.0                                      1.0.1 ·
  fileset 0.2.x                                                     0.2.1 ✓
  js-yaml 3.x                                                       3.6.1 ✓
  git-tools ^0.1.4                                                finding ·
  uglify-js ^2.6.0                                                finding ·
  git-repo-info ^1.0.4                                              1.0.6 ✓
  ember-cli-sri ^2.1.0                                            finding · nal command,
  utf-8-validate@1.2.1! operable program or batch file.
  bufferutil@1.2.1! 'node-gyp' is not recognized as an internal or external command,
  ember-cli-app-version ^1.0.0                                      1.0.0 ✓
  ember-disable-prototype-extensions ^1.1.0                         1.1.0 ·
  mime-types ~2.1.11                                              finding ·
  has-ansi ^2.0.0                                                 finding ·
  babel-plugin-htmlbars-inline-precompile ^0.1.0                  finding ·
  setprototypeof 1.0.1                                              1.0.1 ·
  depd ~1.1.0                                                     finding ·
  exit 0.1.2                                                        0.1.2 ✓
  iconv-lite ~0.4.13                                               0.4.13 ✓
  argparse ^1.0.7                                                   1.0.7 ✓
  content-type ~1.0.2                                             finding ·
  domhandler 2.3                                                    2.3.0 ✓
  escape-html ~1.0.3                                              finding ·
  readable-stream 1.1                                              1.1.14 ✓
  parseurl ~1.3.1                                                 finding ·
  qs 6.2.0                                                        finding ·
  ember-inflector ^1.9.4                                            1.9.6 ✓
  uglify-js ^2.6                                                    2.7.0 ✓
  setprototypeof 1.0.1                                              1.0.1 ✓
  ember-cli-app-version ^1.0.0                                      1.1.1 ·
  broccoli-concat ^2.2.0                                          finding ·
  domelementtype ~1.1.1                                             1.1.1 ✓
  ember-cli-app-version ^1.0.0                                    finding ·
  ember-cli-app-version ^1.0.0                                    finding ·
  sane ^1.1.1                                                     finding ·
  depd ~1.1.0                                                     finding ·
  git-repo-version 0.3.0                                          finding ·
  matcher-collection ^1.0.1                                         1.0.3 ✓
  rimraf ^2.2.8                                                   finding ·
  on-finished ~2.3.0                                              finding ·
  cpr 0.4.2                                                         0.4.2 ✓
  diff ^2.2.2                                                       2.2.3 ✓
  semver ^4.3.1                                                   finding ·
  graceful-fs ^4.1.2                                              finding ·
  minimist ^1.1.2                                                 finding ·
  ember-export-application-global ^1.0.5                            1.0.5 ✓
  has-ansi ^2.0.0                                                   2.0.1 ✓
  prelude-ls ~1.1.2                                               finding ·
  walker ~1.0.5                                                   finding ·
  inquirer ^0.12.0                                                 0.12.0 ·
  leek 0.0.21                                                      0.0.21 ·
  markdown-it 4.3.0                                     downloading 4.3.0 ↓
  nopt ^3.0.1                                                       3.0.6 ✓
  ansi-styles ~1.0.0                                              finding ·
  npm 2.14.21                                         downloading 2.14.21 ↓
  raw-body ~2.1.7                                                 finding ·
  rimraf ^2.4.4                                                     2.5.4 ✓
  temp 0.8.3                                                        0.8.3 ✓
  testem ^1.6.0                                        downloading 1.10.3 ↓
  on-finished ~2.3.0                                              finding ·
  minimist ^1.1.2                                                   1.1.2 ✓
  ee-first 1.1.1                                                    1.1.1 ·
  ember-cli-app-version ^1.0.0                                      1.2.1 ·
  mkdirp ^0.5.0                                                     0.5.0 ·
  broccoli-plugin ^1.2.1                                            1.4.1 ·
  ember-export-application-global ^1.0.5                          finding ·
  is-utf8 ^0.2.0                                                    0.2.0 ·
  bower-endpoint-parser 0.2.2                                     finding ·
  is-utf8 ^0.2.0                                                    0.2.0 ✓
  bower-endpoint-parser 0.2.2                                queued 0.2.2 ↓
  quick-temp ^0.1.5                                                 0.1.5 ✓
  mute-stream 0.0.4                                                 0.0.4 ✓
  graceful-fs ^4.1.4                                                4.1.5 ✓
  minimist ^1.1.2                                                 finding ·
  uglify-js ^2.6.0                                                finding ·
  accepts ~1.3.3                                                    1.3.3 ✓
  bytes 2.3.0                                                       2.3.0 ✓
  compressible ~2.0.8                                               2.0.8 ✓
  fs-extra ^0.24.0                                                 0.24.0 ✓
  eventemitter3 1.x.x                                               1.0.0 ✓
  colors ~0.6.0-1                                                   0.6.2 ✓
  rimraf ^2.4.4                                                   finding ·
  merge ^1.1.3                                                    finding ·
  domelementtype ~1.1.1                                             1.1.1 ✓
  ansi-styles ~1.0.0                                              finding ·
  depd ~1.1.0                                                     finding ·
  mkdirp ~0.5.0                                                     0.5.6 ✓
  markdown-it 4.3.0                                                 4.3.0 ✓
  mkdirp ~0.5.0                                                     0.5.0 ·
  ember-cli-app-version ^1.0.0                                      1.0.0 ·
  loader.js ^4.0.1                                                finding ·
  prelude-ls ~1.1.2                                                 1.1.2 ✓
  minimatch ^2.0.1                                                  2.0.1 ✓
  matcher-collection ^1.0.1                                       finding ·
  concat-map 0.0.1                                      downloading 0.0.1 ↓
  glob ^6.0.1                                                       6.0.4 ✓
  negotiator 0.6.1                                                  0.6.1 ✓
  figures ^1.3.5                                                    1.7.0 ✓
  ember-cli-app-version ^1.0.0                                    finding ·
  has-color ~0.1.0                                                finding ·
  broccoli-writer ~0.1.1                                          finding ·
  ember-cli-app-version ^1.0.0                                    finding ·
  strip-ansi ^3.0.0                                                 3.9.1 ✓
  through ~2.3.8                                                    2.3.8 ✓
  cookie-signature 1.0.6                                            1.0.6 ✓
  loader.js ^4.0.1                                                  4.0.1 ✓
  etag ~1.7.0                                                       1.7.0 ✓
  has-ansi ^2.0.0                                                   2.0.1 ·
  utils-merge 1.0.0                                               finding ·
  mute-stream 0.0.4                                               finding ·
  ember-disable-prototype-extensions ^1.1.0                       finding ·
  has-color ~0.1.0                                                finding ·
  broccoli-kitchen-sink-helpers ~0.2.0                            finding ·
  setprototypeof 1.0.1                                            finding ·
  parseurl ~1.3.0                                                   1.3.0 ✓
  ember-cli-app-version ^1.0.0                                      1.0.2 ✓
  source-map 0.1.32                                                0.1.32 ✓
  has-ansi ^2.0.0                                                   2.0.0 ✓
  xtend ^4.0.0                                                      4.0.0 ✓
  utils-merge 1.0.0                                          queued 1.0.0 ↓
  setprototypeof 1.0.1                                            finding ·
  exists-sync 0.0.3                                          queued 0.0.3 ↓
  mute-stream 0.0.4                                               finding ·
  lodash 3.7.x                                                      3.7.0 ·
  raw-body ~2.1.5                                                   2.1.7 ✓
  npm 2.14.21                                                     2.14.21 ·
  glob ^5.0.15                                                     5.0.15 ✓
  os-tmpdir ~1.0.1                                                     OK ✓
  recast ^0.10.0                                                  0.10.43 ✓
  ast-types 0.8.15                                                 0.8.15 ✓
  aws-sign2 ~0.6.0                                                  0.6.0 ✓
  ansi-styles ~1.0.0                                                   OK ✓
  extend ~3.0.0                                                     3.0.0 ✓
  content-type ~1.0.2                                                  OK ✓
  form-data ~1.0.0-rc4                                          1.0.0-rc4 ✓
  inherits ~2.0.1                                                      OK ✓
  hawk ~3.1.3                                                       3.1.3 ✓
  isstream ~0.1.2                                                   0.1.2 ✓
  source-map ~0.5.1                                                    OK ✓
  extend ~3.0.0                                                        OK ✓
  oauth-sign ~0.8.1                                                 0.8.2 ✓
  content-type ~1.0.2                                                  OK ✓
  stringstream ~0.0.4                                               0.0.5 ✓
  tunnel-agent ~0.4.1                                               0.4.3 ✓
  isstream ~0.1.2                                                      OK ✓
  deep-is ~0.1.3                                                       OK ✓
  recast ^0.11.3                                                  0.11.11 ✓
  ansicolors ~0.2.1                                                 0.2.1 ✓
  readable-stream ~2.0.5                                            2.0.6 ✓
  mime-types ^2.1.10                                               2.1.11 ✓
  qs ~5.1.0                                                            OK ✓
  verror 1.3.6                                                      1.3.6 ✓
  broccoli-kitchen-sink-helpers ~0.2.0                                 OK ✓
  ast-types 0.8.18                                                 0.8.18 ✓
  os-tmpdir ~1.0.1                                                     OK ✓
  commander ^2.9.0                                                  2.9.0 ✓
  ember-cli 2.5.0                                                   2.5.0 ✓
  bluebird ^3.4.0                                                   3.4.1 ✓
  consolidate ^0.14.0                                              0.14.1 ✓
  did_it_work 0.0.6                                                    OK ✓
  express ^4.10.7                                                  4.14.0 ✓
  fireworm ^0.7.0                                                   0.7.1 ✓
  glob ^7.0.4                                                       7.0.5 ✓
  http-proxy ^1.13.1                                               1.14.0 ✓
  js-yaml ^3.2.5                                                    3.6.1 ✓
  socket.io 1.4.7                                                   1.4.7 ✓
  xmldom ^0.1.19                                                   0.1.22 ✓
  boom 2.x.x                                                       2.10.1 ✓
  process-nextick-args ~1.0.6                                       1.0.7 ✓
  gauge ~2.6.0                                                      2.6.0 ✓
  set-blocking ~2.0.0                                               2.0.0 ✓
  bluebird ^3.1.1                                                   3.4.1 ✓
  esprima-fb ~12001.1.0-dev-harmony-fb           12001.1.0-dev-harmony-fb ✓
  underscore >=1.8.3                                                1.8.3 ✓
  which ^1.2.9                                                     1.2.10 ✓
  async ~0.2.9                                                     0.2.10 ✓
  readable-stream ^2                                                2.1.4 ✓
  js-yaml ^3.2.7                                                    3.6.1 ✓
  engine.io 1.6.10                                                 1.6.10 ✓
  socket.io-parser 2.2.6                                            2.2.6 ✓
  socket.io-client 1.4.6                                            1.4.6 ✓
  socket.io-adapter 0.4.0                                           0.4.0 ✓
  readable-stream ^2.0.0 || ^1.1.13                                 2.1.4 ✓
  tweetnacl ~0.13.0                                                0.13.3 ✓
  asn1 ~0.2.3                                                       0.2.3 ✓
  dashdash ^1.12.0                                                 1.14.0 ✓
  commander 2.8.x                                                   2.8.1 ✓
  source-map 0.4.x                                                  0.4.4 ✓
  socket.io-parser 2.2.2                                            2.2.2 ✓
  json3 3.3.2                                                       3.3.2 ✓
  component-emitter 1.1.2                                           1.1.2 ✓
  engine.io-client 1.6.9                                            1.6.9 ✓
  component-emitter 1.2.0                                           1.2.0 ✓
  to-array 0.1.4                                                    0.1.4 ✓
  jsonpointer 2.0.0                                                 2.0.0 ✓
  stringmap ~0.2.2                                                  0.2.2 ✓
  yargs ~3.27.0                                                    3.27.0 ✓
  engine.io-parser 1.2.4                                            1.2.4 ✓
  accepts 1.1.4                                                     1.1.4 ✓
  debug 0.7.4                                                       0.7.4 ✓
  json3 3.2.6                                                       3.2.6 ✓
  negotiator 0.4.9                                                  0.4.9 ✓
  mime-types ~2.0.4                                                2.0.14 ✓
  mime-db ~1.12.0                                                  1.12.0 ✓
  xmlhttprequest-ssl 1.5.1                                          1.5.1 ✓
  after 0.8.1                                                       0.8.1 ✓
  has-binary 0.1.6                                                  0.1.6 ✓
  marked ^0.3.2                                                     0.3.6 ✓
  marked-terminal ^1.6.1                                            1.6.1 ✓
  abbrev ~1.0.7                                                        OK ✓
  ansi ~0.3.1                                                          OK ✓
  columnify ~1.5.4                                                     OK ✓
  cmd-shim ~2.0.2                                                      OK ✓
  config-chain ~1.1.10                                                 OK ✓
  fs-vacuum ~1.2.7                                                     OK ✓
  fstream ~1.0.8                                                       OK ✓
  github-url-from-git ~1.4.0                                           OK ✓
  glob ~5.0.15                                                         OK ✓
  graceful-fs ~4.1.3                                                   OK ✓
  ini ~1.3.4                                                           OK ✓
  init-package-json ~1.9.3                                             OK ✓
  lru-cache ~3.2.0                                                     OK ✓
  hosted-git-info ~2.1.4                                               OK ✓
  node-gyp ~3.3.0                                                      OK ✓
  normalize-git-url ~3.0.1                                             OK ✓
  npm-package-arg ~4.1.0                                               OK ✓
  npm-registry-client ~7.0.9                                           OK ✓
  normalize-package-data ~2.3.5                                        OK ✓
  opener ~1.4.1                                                        OK ✓
  readable-stream ~1.1.13                                              OK ✓
  read-installed ~4.0.3                                                OK ✓
  request ~2.69.0                                                      OK ✓
  read-package-json ~2.0.3                                             OK ✓
  retry ~0.9.0                                                         OK ✓
  rimraf ~2.5.2                                                        OK ✓
  slide ~1.1.6                                                         OK ✓
  tar ~2.2.1                                                           OK ✓
  validate-npm-package-name ~2.2.2                                     OK ✓
  which ~1.2.4                                                         OK ✓
  write-file-atomic ~1.1.4                                             OK ✓

C:\projects\ember-dds>ember serve
DEPRECATION: ember-try is now included with ember-cli. Including it in your package.json is unnecessary.
Cannot find module 'glob'
Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (C:\projects\ember-dds\server\index.js:13:20)
    at Class.module.exports.Task.extend.processAppMiddlewares (C:\projects\ember-dds\node_modules\.store\ember-cli@2.5.0\_\lib\tasks\server\express-server.js:126:14)
    at Class.<anonymous> (C:\projects\ember-dds\node_modules\.store\ember-cli@2.5.0\_\lib\tasks\server\express-server.js:220:21)
    at lib$rsvp$$internal$$tryCatch (C:\projects\ember-dds\node_modules\.store\rsvp@3.2.1\_\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\projects\ember-dds\node_modules\.store\rsvp@3.2.1\_\dist\rsvp.js:1048:17)
    at C:\projects\ember-dds\node_modules\.store\rsvp@3.2.1\_\dist\rsvp.js:331:11
```

**Comment by zkochan** [comment] 2016-08-13 18:15
OK, at least the installation issue is gone.

Whe using [this steps](https://github.com/rstacruz/pnpm/issues/292#issuecomment-239617980) I cannot reproduce. Maybe you have some custom server setup code?

**Comment by zkochan** [comment] 2016-09-02 13:39
What was your version of NodeJS when the issue was happening?

**Comment by zkochan** [comment] 2016-09-02 13:41
By the way, the initial issue was fixed in v0.29.0.

The other one that happens on `ember serve` I could not repro yet

**Comment by zkochan** [comment] 2016-10-02 22:40
@BryanCrotaz could you retry this with [v0.38.0](https://github.com/rstacruz/pnpm/releases/tag/v0.38.0)? It has a fix for https://github.com/rstacruz/pnpm/issues/380 which might be related to this one, as I see the same problematic package in your deps

**Comment by connorhartley** [comment] 2016-10-02 23:36
This happens to me as well, even on v0.38.0.

**Comment by iamstarkov** [comment] 2016-10-03 13:40
is original issue gone?

**Comment by zkochan** [comment] 2016-10-17 19:07
The last issue in this thread is going to be fixed by #403

**Comment by zkochan** [comment] 2016-10-19 05:46
@BryanCrotaz we released the possibility to install dependencies flat in v0.42.0 (under the next dist-tag for now). Run pnpm install with the `--flat-tree` option and the issue will dissappear

**Closed by zkochan** 2016-10-19 05:46 UTC
Labels: bug

**Comment by zkochan** [comment] 2016-10-19 06:19
This might be a temporal workaround before #433 is done

**Comment by BryanCrotaz** [comment] 2016-10-19 14:17
Workaround doesn't work on node 4.3 (the standard version on CI servers) - 6.3 not rolled out yet.

**Comment by zkochan** [comment] 2016-10-19 21:07
ok, created a new issue to figure this out #436
