### ISSUE TITLE
Use registry url configured in npm

### ISSUE THREAD

**Issue by forabi** [rstacruz/pnpm#13] opened 2016-01-29 11:30 UTC
This will be useful for local npm mirrors like sinopia, and could lead to significant speed boost in downloads.

```shell
> npm config get registry
http://localhost:4873/
```

**Comment by rstacruz** [comment] 2016-01-29 11:38
dupe of #10, thanks!

**Closed by rstacruz** 2016-01-29 11:38 UTC

**Comment by forabi** [comment] 2016-01-29 11:41
Great! :+1:
