### ISSUE TITLE
Is it possible that we need to clear npm cache after installing this?

### ISSUE THREAD

**Issue by niftylettuce** [rstacruz/pnpm#186] opened 2016-04-22 22:56 UTC
I constantly get these errors in ubuntu build environments after I did `npm i -g pnpm` and then changed my build line from `npm install` to `pnpm install`, e.g:

`! EINVAL: invalid argument, readlink`

``` log
has-ansi 2.0.0
lodash.keys 3.1.2
split 0.3.3
minimist 1.2.0
node-uuid 1.4.7
event-stream 3.3.2
lodash.template 3.6.2
lodash._reinterpolate 2.4.1
through2 0.6.5
raven 0.8.1
readable-stream 1.0.34
clone 1.0.2
isarray 0.0.1

 ! EINVAL: invalid argument, readlink '/var/www/staging/source/node_modules/winston-sentry'

  post-deploy hook failed
```

**Comment by zkochan** [comment] 2016-10-20 21:22
@niftylettuce is it still reproducible with the latest pnpm? A lot of code was rewritten since April.

**Comment by niftylettuce** [comment] 2016-10-20 22:24
Umm I could try, I was going to try using `yarn` since it's all the rage, but I ran into this issue <https://github.com/yarnpkg/yarn/issues/872> haha.  I don't think this happens with `pnpm` though 👍 📦 🚢 :shipit:

**Comment by zkochan** [comment] 2017-01-09 22:45
I close it for now because almost everything has been rewritten in pnpm, since the issue was created. But if someone will have the same issues, we can reopen it

**Closed by zkochan** 2017-01-09 22:45 UTC
Labels: might be fixed already

**Comment by BrianAdams** [comment] 2017-03-03 17:52
Ran in to this today:

>ERROR EINVAL: invalid argument, readlink '/Users/brian/project/node_modules/binary-parser'

`pnpm --version`
>0.58.0

Just to note, npm clear cache did not help.

**Comment by zkochan** [comment] 2017-03-03 17:59
You probably used npm on the project previously and it created the `binary-parser` folder. Try to remove node_modules and try again with `pnpm install`

**Comment by BrianAdams** [comment] 2017-03-03 18:08
Removing node_modules after a propr npm install appears to have fixed the above error. Thanks!

**Comment by zkochan** [comment] 2017-03-03 18:09
Cool, I'll add a more meaningful error message for this issue
