### ISSUE TITLE
uid must be an unsigned int

### ISSUE THREAD

**Issue by freeman29** [rstacruz/pnpm#83] opened 2016-02-03 09:22 UTC
pnpm is awesome.. but I'm having issue on installing.. please help.

Issue:
 binding.chown(pathModule._makeLong(path), uid, gid, req);
          ^

TypeError: uid must be an unsigned int
    at TypeError (native)
    at fs.chown (fs.js:1082:11)
    at /usr/local/lib/node_modules/pnpm.js/node_modules/tar-fs/index.js:215:7
    at FSReqWrap.oncomplete (fs.js:83:15)

**Comment by rstacruz** [comment] 2016-02-03 09:23
How'd you get that? Can I see your package.json?

**Comment by rstacruz** [comment] 2016-02-03 09:25
And what's your os and npm/node versions?

$ npm version

**Comment by freeman29** [comment] 2016-02-03 09:29
OS: Linux Mint
Node: v5.2.0
npm: 3.3.12

package.json: i'm using react-slingshot starter kit

{
  "name": "react-slingshot",
  "version": "1.1.1",
  "description": "Starter kit for creating apps with React and Redux",
  "scripts": {
    "prestart": "npm run remove-dist",
    "start": "parallelshell \"npm run lint:tools\" \"npm run test:watch\" \"npm run open:src\"",
    "open:src": "node tools/srcServer.js",
    "open:dist": "node tools/distServer.js",
    "lint:tools": "eslint webpack.config.js tools",
    "clean-dist": "npm run remove-dist && mkdir dist",
    "remove-dist": "node_modules/.bin/rimraf ./dist",
    "build:html": "node tools/buildHtml.js",
    "prebuild": "npm run clean-dist && npm run build:html",
    "build": "npm run test && node tools/build.js && npm run open:dist",
    "test": "cross-env NODE_ENV=test mocha --reporter progress --compilers js:babel/register --recursive \"./src/**/*.spec.js\"",
    "test:watch": "npm run test -- --watch"
  },
  "author": "Cory House",
  "license": "MIT",
  "dependencies": {
    "object-assign": "4.0.1",
    "react": "0.14.6",
    "react-dom": "0.14.6",
    "react-redux": "4.0.6",
    "redux": "3.0.5"
  },
  "devDependencies": {
    "babel": "5.8.23",
    "babel-eslint": "4.1.7",
    "babel-loader": "5.1.4",
    "babel-plugin-react-display-name": "2.0.0",
    "babel-plugin-react-transform": "1.1.1",
    "browser-sync": "2.11.1",
    "chai": "3.4.1",
    "cheerio": "0.19.0",
    "colors": "1.1.2",
    "cross-env": "1.0.7",
    "css-loader": "0.23.1",
    "eslint": "1.10.3",
    "eslint-loader": "1.2.0",
    "eslint-plugin-react": "3.15.0",
    "extract-text-webpack-plugin": "1.0.1",
    "file-loader": "0.8.5",
    "mocha": "2.3.4",
    "node-sass": "3.4.2",
    "parallelshell": "2.0.0",
    "react-transform-catch-errors": "1.0.1",
    "react-transform-hmr": "1.0.1",
    "redbox-react": "1.2.0",
    "rimraf": "2.5.0",
    "sass-loader": "3.1.2",
    "style-loader": "0.13.0",
    "watch": "0.17.1",
    "webpack": "1.12.11",
    "webpack-dev-middleware": "1.4.0",
    "webpack-hot-middleware": "2.6.0",
    "yargs": "3.32.0"
  },
  "keywords:": [
    "react",
    "reactjs",
    "hot",
    "reload",
    "hmr",
    "live",
    "edit",
    "webpack",
    "redux",
    "flux",
    "boilerplate",
    "starter"
  ]
}

**Comment by Ingramz** [comment] 2016-02-03 12:29
Also possible to reproduce using following docker one-liner:
`docker run --rm  node:latest /bin/bash -c "npm install -g pnpm; pnpm install laravel-elixir@^4.0.0"`

```
npm info using npm@3.3.12
npm info using node@v5.5.0
```

**Comment by rstacruz** [comment] 2016-02-03 12:30
shudder... let's see.

**Comment by rstacruz** [comment] 2016-02-03 12:30
also, super clever with that docker one-liner, kudos!

**Comment by brotchie** [comment] 2016-02-17 02:49
Turns out this was an issue with the `tar-stream` package required by pnpm's `tar-fs` dependency. tar-stream didn't support parsing large uids and gids, instead returning NaN values. 

I've submitted a pull request https://github.com/mafintosh/tar-stream/pull/47 and this issue should be fixed once it's merged and published to npm.

This command now succeeds when you force npm to use my patched version of tar-stream:
```
docker run --rm node:latest /bin/bash -c "npm install -g brotchie/tar-stream pnpm; pnpm install laravel-elixir@^4.0.0"
```

**Comment by Ingramz** [comment] 2016-02-17 16:07
The change in tar-stream has been merged and and a release has been made, which has automatically propagated to pnpm, so I believe this issue can be closed.

**Comment by rstacruz** [comment] 2016-02-17 17:29
Nice work @brotchie!

**Closed by rstacruz** 2016-02-17 17:29 UTC

**Comment by freeman29** [comment] 2016-02-18 00:30
Good job James..
