### ISSUE TITLE
Install from GitHub

### ISSUE THREAD

**Issue by rstacruz** [rstacruz/pnpm#20] opened 2016-01-29 21:01 UTC
`npm install rstacruz/scourjs`

Okay, this is a tough one. I don't even know where to begin describing this... sorry, will come back to it later

**Comment by rstacruz** [comment] 2016-01-29 22:25
Also, github modules should not be stored in the `modulename@version` format. they should have their own id's based on the unambiguous reference, eg:

```
node_modules/.store/git!!!github.com!rstacruz!scour.git#dff12e44b155613e000f1200f5069bfead7d459d
```

also keep note that some modules have a different github name than the module name. eg, `pnpm.js` is in `rstacruz/pnpm` (instead of `rstacruz/pnpm.js`), so that'd have to be accounted for, too:

```
node_modules/pnpm.js ->
node_modules/.store/git!!!github.com!rstacruz!pnpm.git#fc20f75c9e6e7e551dd00018f27eea1b17b3c3bf
```

**Comment by halhenke** [comment] 2016-02-01 12:27
I might take a shot at this. Was taking a look at how npm does git repos earlier. Things seem to be progressing super quickly though so half expect to see a PR from someone by the time I get started :smiley:

**Comment by rstacruz** [comment] 2016-02-01 13:02
It's complicated but try!

**Comment by halhenke** [comment] 2016-02-01 21:06
Heh :-) 

OK - I'm committed now. Will work on it over next couple of days.

**Comment by rstacruz** [comment] 2016-02-02 03:45
btw, have a look at `lib/resolve/tarball.js` to see how its handled for `http://site.com/foo.tgz` tarballs. it saves to the format of:

```
node_modules/.store/in-array-1.0.1#fc20f75c9e6e7e551dd00018f27
```

where the hex number is a hash of the URL it was fetched from. I'm guessing git urls should be handled similarly, ie:

```
node_modules/.store/halhenke-jade-react-loader#fc20f75c9e6e7e551dd00018f27
```

where the hex number is a hash of the git URL.

**Comment by halhenke** [comment] 2016-02-02 14:12
OK. I was thinking of doing a bare/mirror clone - just getting the git repository first - and then doing one or more clones from that local version of the repository to get the actual code - mostly in case there were dependencies on different tags/commits from the same repository. However since there are no longer plans to link everything from a global node_modules folder this seems a lot less likely.

**Comment by defunctzombie** [comment] 2016-02-02 23:53
Just wanted to add the lesser known syntax(es) also supported by npm:

```
npm install github:user/repo
npm install github:user/repo#30a8274b
```

**Comment by rstacruz** [comment] 2016-02-02 23:54
and `bitbucket:a/b`! btw, npm-package-arg will take care of these for you

**Comment by thangngoc89** [comment] 2016-02-22 21:32
I suggest we resolve the commit hash via Github API and download tarball. This would be better, involving with git is complicated.

**Comment by rstacruz** [comment] 2016-02-22 21:40
Is it possible? Last I checked you can't download a tar ball of a commit Id

**Comment by thangngoc89** [comment] 2016-02-22 21:46
Example with bootstrap

https://github.com/twbs/bootstrap/archive/6ec9aa34a4b6d43b593b97f9b207410eff8f0152.tar.gz

**Comment by thangngoc89** [comment] 2016-02-22 21:48
Your master branch 
https://github.com/rstacruz/pnpm/archive/21e71acf598bdf78eaf9d5915e0f5d2fceb8acb8.tar.gz

We can replace commit hash with brach name

**Comment by halhenke** [comment] 2016-02-22 22:16
Hey, sorry for the lateness in getting back to you on this - had to take a bit of a break on other stuff. 

I was reluctant to do anything that relied on GitHub's API because that wouldnt cover other valid npm cases that involve non-Github git repos. Tarballs would be nice because they fit into the existing design which, from memory. is based around streaming files whereas, from what I've seen, git clone involves a fair bit of handshake logic etc that would suck to reproduce (and I haven't seen in any library).

So where this is at, at the moment was using the shell version of git and trying to extract progress information (doable but a bit ugly) and hopefully slot it into the rest of the workflow as seamlessly as I could. Not sure if that sounds sensible or not.

At any rate will try to finish this week though am happy to hand over to anyone who might have a better handle on the issues.

**Comment by dbkaplun** [comment] 2016-07-25 16:47
Just ran into this issue. It seems I can't use pnpm to install these dependencies so I think this is a blocker. Should pass through to npm, at least until native git support is added.

**Comment by zkochan** [comment] 2016-07-26 20:20
@dbkaplun are the packages you need not on GitHub? For GitHub-hosted packages `pnpm install` was implemented.

It is a pretty tough task to make it work in all the possible scenarios. npm's code for installing packages from git has almost 500 lines https://github.com/npm/npm/blob/9e03561547ec5830c5f61caa4e6221d4d3b813aa/lib/cache/add-remote-git.js

**Comment by zkochan** [comment] 2016-09-27 07:24
@dbkaplun you can try to install the latest pnpm. Native GIT support was added in v0.35.0

(NOTE: currently your package has to be in the root of the GIT repo that you require)

**Closed** 2016-09-29 18:58 UTC
Labels: help wanted

**Comment by geekguy** [comment] 2016-10-02 08:58
@zkochan If we point to some to some github commit hash, pnpm doesn't work properly.

Example:
```json
{
"somepackage": "git://github.com/geekguy/somepackage.git#133a02",
}
```

When we do pnpm install, it throws following error.
```
 ! failed to clone repository from git+ssh://git://github.com/geekguy/somepackage.git
        Cloning into '/tmp/deploy/test/node_modules/.store/git+ssh:..
warning: Could not find remote branch 133a02 to clone.
fatal: Remote branch 133a02 not found in upstream origin
```

Is there any workaround for this?

**Comment by zkochan** [comment] 2016-10-02 14:41
@geekguy are you sure the commit hash that you used exists?

I've tried with `"applyq": "git://github.com/zkochan/applyq#ff931e"` and it worked fine

**Comment by geekguy** [comment] 2016-10-02 18:42
@zkochan : Interestingly it worked after I removed `.git` from the link. It's not happening any more (even with `.git`). I ll update if I am able to reproduce it.

Thanks.

**Comment by aquaductape** [comment] 2021-05-21 07:10
I created a fork of package.
Here's 3 different ways I tried to install my fork, but instead it keeps installing the original.  With `npm` and `yarn` it works.

```
 1. "fusioncharts": "https://github.com/aquaductape/fusioncharts-dist.git"
 2. "fusioncharts": "github:aquaductape/fusioncharts-dist"
 3. "fusioncharts": "aquaductape/fusioncharts-dist",
```

**Comment by loeffel-io** [comment] 2022-05-30 11:03
```
"termynal": "git://github.com/ines/termynal#9b30189",
```

isn't working
